### ISSUE TITLE
Looks interesting... is the project still active?

### ISSUE THREAD

**Issue by mvdkleijn** [swampapp/swamp#44]
This looks really interesting in combination with my Restic setup. However, the project didn't have any commits since about January 2023... is it still active / planned to go forward?

**Comment by rubiojr** [comment]
@mvdkleijn not really I'm afraid, following upstream Restic changes is very time consuming (very active project) and I had to abandon the idea for now.

**Comment by mvdkleijn** [comment]
OK, a shame but understandable. 👍
